[package]
name = "nvimkata"
version = "0.1.2"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
toml = "1.0.3"
